concourse-db:
  image: postgres:9.5
  environment:
    POSTGRES_DB: concourse
    POSTGRES_USER: concourse
    POSTGRES_PASSWORD: changeme
    PGDATA: /database

concourse-web:
  image: concourse/concourse
  links: [concourse-db, nexus]
  command: web
  ports: ["8080:8080"]
  volumes: ["./keys/web:/concourse-keys"]
  environment:
    CONCOURSE_BASIC_AUTH_USERNAME: concourse
    CONCOURSE_BASIC_AUTH_PASSWORD: changeme
    CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
    CONCOURSE_POSTGRES_DATA_SOURCE: |-
      postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable

concourse-worker:
  image: concourse/concourse
  privileged: true
  links: [concourse-web, nexus]
  command: worker
  volumes: ["./keys/worker:/concourse-keys"]
  environment:
    CONCOURSE_TSA_HOST: concourse-web

nexus:
  image: sonatype/nexus3
  ports: ["8081:8081"]


# http://jgsqware.github.io/2015/11/draft/sonarqube-with-postgresql-on-docker/

sonarqube:
  image: sonarqube
  ports:
   - "9000:9000"
   - "5432:5432"
  links:
    - sonardb:sonardb
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar

sonardb:
  image: postgres
  environment:
   - POSTGRES_DB=sonar
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
  # volumes:
  #  - postgresql:/var/lib/postgresql
  #   # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
  #  - postgresql_data:/var/lib/postgresql/data
